from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
ASSETS_DIR = PROJECT_ROOT / "assets"
TEMPLATES_DIR = PROJECT_ROOT / "templates"
OUTPUT_DIR = PROJECT_ROOT / "output"

DOCUMENT_FONT_SIZE_PT = 13
JAPANESE_FONT_SIZE_PT = 12
VIETNAMESE_FONT = "Times New Roman"
JAPANESE_FONT = "Yu Gothic"
LINE_SPACING_TWIPS = 360
TABLE_LINE_SPACING_TWIPS = 240
TABLE_CELL_VERTICAL_MARGIN_TWIPS = 120

PAGE_WIDTH_CM = 14.8
PAGE_HEIGHT_CM = 21.0
TOP_MARGIN_CM = 1.5
BOTTOM_MARGIN_CM = 1.5
LEFT_MARGIN_CM = 1.0
RIGHT_MARGIN_CM = 1.5
GUTTER_CM = 1.0
